#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path


def read_jsonl(path: str):
    rows = []
    with open(path, 'r', encoding='utf-8', errors='ignore') as f:
        for line in f:
            if line.strip():
                rows.append(json.loads(line))
    return rows


def main() -> None:
    ap = argparse.ArgumentParser(description='Run CosyVoice TTS tasks generated by 01_make_question_tts_tasks.py')
    ap.add_argument('--repo', default='/data/zeynliu/repos/CF-Duplex')
    ap.add_argument('--tasks', required=True)
    ap.add_argument('--model_dir', required=True)
    ap.add_argument('--work_dir', required=True)
    ap.add_argument('--gpus', default='0')
    ap.add_argument('--procs_per_gpu', type=int, default=1)
    ap.add_argument('--conda_env', default='')
    ap.add_argument('--python_bin', default='')
    ap.add_argument('--cosyvoice_repo', default='')
    ap.add_argument('--model_class', default='auto')
    ap.add_argument('--sr', type=int, default=16000)
    args = ap.parse_args()

    repo = Path(args.repo)
    sys.path.insert(0, str(repo / 'data_pipeline'))
    from uaf.tts import submit_tts_jobs  # type: ignore

    tasks = read_jsonl(args.tasks)
    gpus = [int(x) for x in args.gpus.split(',') if x.strip()]
    if not gpus:
        raise SystemExit('empty --gpus')
    if args.cosyvoice_repo:
        os.environ['COSYVOICE_REPO'] = args.cosyvoice_repo

    results = submit_tts_jobs(
        tasks=tasks,
        model_dir=args.model_dir,
        gpus=gpus,
        work_dir=args.work_dir,
        conda_env=args.conda_env,
        sr=args.sr,
        model_class=args.model_class,
        procs_per_gpu=args.procs_per_gpu,
        python_bin=args.python_bin,
        cosyvoice_repo=args.cosyvoice_repo,
    )
    ok = sum(1 for r in results if r.get('status') in ('ok', 'cached'))
    err = [r for r in results if r.get('status') not in ('ok', 'cached')]
    out = Path(args.work_dir) / 'tts_results.jsonl'
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open('w', encoding='utf-8') as f:
        for r in results:
            f.write(json.dumps(r, ensure_ascii=False) + '\n')
    print(json.dumps({'tasks': len(tasks), 'ok_or_cached': ok, 'errors': len(err), 'result_file': str(out)}, ensure_ascii=False, indent=2))
    if err:
        print(json.dumps({'first_errors': err[:5]}, ensure_ascii=False, indent=2))


if __name__ == '__main__':
    main()
